FROM python:3.7-stretch

RUN git clone --depth 1 https://github.com/tetherless-world/tw-nanopub.git /tw-nanopub
RUN cd /tw-nanopub/py && python3 setup.py install

COPY /py /twdb/py
WORKDIR /twdb/py
RUN pip3 install -r requirements.txt
RUN python3 setup.py install

CMD ["tail", "-f", "/dev/null"]
