#!/bin/bash

#!/bin/sh
MYSELF=$(which "$0" 2>/dev/null)
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
  java="$JAVA_HOME/bin/java"
fi
exec "$java" -Dedu.rpi.tw.twks.client.baseUrl=http://twks-server:8080 -jar $MYSELF "$@"
exit 1
