#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment in py/venv"
    python3 -m venv venv
fi
echo "Activating Python virtual environment"
source venv/bin/activate
echo "Installing Python dependencies"
pip3 install -r requirements.txt
